From ubuntu:14.04
## Install redis
RUN apt-get update
RUN apt-get upgrade -yqq
RUN apt-get install -yqq build-essential gcc g++ openssl wget curl git-core libssl-dev libc6-dev ruby

RUN gem install redis
RUN wget http://download.redis.io/redis-stable.tar.gz
RUN tar xvzf redis-stable.tar.gz
WORKDIR /redis-stable/src/

