{% set name = "mmh3" %}
{% set version = "2.5.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "185209a217c52afe43e079e5b232d0ef0f3a262601eaaf4371326ab6dcbec508" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

about:
  home: http://packages.python.org/mmh3
  license: 'License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication'
  license_family: CC
  license_file: ''
  summary: Python wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.
  description: "mmh3\n====\n\n.. image:: https://img.shields.io/travis/hajimes/mmh3.svg?branch=master\n   :target: https://travis-ci.org/hajimes/mmh3\n\n.. image:: https://ci.appveyor.com/api/projects/status/github/hajimes/mmh3?branch=master&svg=true\n\
    \   :target: https://ci.appveyor.com/project/hajimes/mmh3\n\nPython wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.\n\nmmh3 2.5.1 supports Python 2.7, Python 3.3 and higher.\n\
    \nUsage\n-----\n\nSample Usage::\n\n    >>> import mmh3\n    >>> mmh3.hash('foo') # 32 bit signed int\n    -156908512\n    >>> mmh3.hash('foo', 42) # uses 42 for its seed\n    -1322301282\n    >>> mmh3.hash('foo',\
    \ signed=False) # 32 bit unsigned int (since Version 2.5)\n    4138058784\n\nOther functions::\n\n    >>> mmh3.hash64('foo') # two 64 bit signed ints (by using the 128-bit algorithm as its backend)\n\
    \    (-2129773440516405919, 9128664383759220103)\n    >>> mmh3.hash64('foo',signed =False) #  two 64 bit unsigned ints\n    (16316970633193145697, 9128664383759220103)\n    >>> mmh3.hash128('foo', 42)\
    \ # 128 bit unsigned int\n    215966891540331383248189432718888555506\n    >>> mmh3.hash128('foo', 42, signed = True) # 128 bit signed int\n    -124315475380607080215185174712879655950\n    >>> mmh3.hash_bytes('foo')\
    \ # 128 bit value as bytes\n    'aE\\xf5\\x01W\\x86q\\xe2\\x87}\\xba+\\xe4\\x87\\xaf~'\n\n``hash64``, ``hash128``, and ``hash_bytes`` have the third argument for architecture optimization. Use True\
    \ for x64 and False for x86 (default: True).::\n\n    >>> mmh3.hash64('foo', 42, True) \n    (-840311307571801102, -6739155424061121879)\n\nVersion 2.5 added ``hash_from_buffer``, which hashes byte-likes\
    \ without memory copying. The method is suitable when you hash a large memory-view such as ``numpy.ndarray``.\n\n    >>> mmh3.hash_from_buffer(numpy.random.rand(100))\n    -2137204694\n    >>> mmh3.hash_from_buffer(numpy.random.rand(100),\
    \ signed = False)\n    3812874078\n\nBeware that ``hash64`` returns **two** values, because it uses the 128-bit version of MurmurHash3 as its backend.\n\nVersion 2.4 added support for 64-bit data.\n\
    \n    >>> import numpy as np\n    >>> a = np.zeros(2**32, dtype=np.int8)\n    >>> mmh3.hash_bytes(a)\n    b'V\\x8f}\\xad\\x8eNM\\xa84\\x07FU\\x9c\\xc4\\xcc\\x8e'\n\nVersion 2.4 also changed the type\
    \ of seeds from signed 32-bit int to unsigned 32-bit int. (**The resulting values with signed seeds still remain the same as before, as long as they are 32-bit**)\n\n    >>> mmh3.hash('aaaa', -1756908916)\
    \ # signed rep. for 0x9747b28c\n    1519878282\n    >>> mmh3.hash('aaaa', 2538058380) # unsigned rep. for 0x9747b28c\n    1519878282\n\nBe careful so that these seeds do not exceed 32-bit. Unexpected\
    \ results may happen with invalid values.\n\n    >>> mmh3.hash('foo', 2 ** 33)\n    -156908512\n    >>> mmh3.hash('foo', 2 ** 34)\n    -156908512\n\n\nChanges\n=======\n2.5.1 (2017-10-31)\n------------------\n\
    * Bug fix for ``hash_bytes``. Thanks `doozr <https://github.com/doozr>`_!\n\n2.5 (2017-10-28)\n------------------\n* Add ``hash_from_buffer``. Thanks `Dimitri Vorona <https://github.com/alendit>`_!\n\
    * Add a keyword argument ``signed``.\n\n2.4 (2017-05-27)\n------------------\n* Support seeds with 32-bit unsigned integers; thanks `Alexander Maznev <https://github.com/pik>`_!\n* Support 64-bit data\
    \ (under 64-bit environments)\n* Fix compile errors for Python 3.6 under Windows systems.\n* Add unit testing and continuous integration with Travis CI and AppVeyor.\n\n2.3.2 (2017-05-26)\n------------------\n\
    * Relicensed from public domain to `CC0-1.0 <./LICENSE>`_.\n\n2.3.1 (2015-06-07)\n------------------\n* Fix compile errors for gcc >=5.\n\n2.3 (2013-12-08)\n----------------\n* Add ``hash128``, which\
    \ returns a 128-bit signed integer.\n* Fix a misplaced operator which could cause memory leak in a rare condition.\n* Fix a malformed value to a Python/C API function which may cause runtime errors\
    \ in recent Python 3.x versions.\n\nThe first two commits are from `Derek Wilson <https://github.com/underrun>`_. Thanks!\n\n2.2 (2013-03-03)\n----------------\n* Improve portability to support systems\
    \ with old gcc (version < 4.4) such as CentOS/RHEL 5.x. (Commit from `Micha Gorelick <https://github.com/mynameisfiber>`_. Thanks!)\n\n2.1 (2013-02-25)\n----------------\n\n* Add `__version__` constant.\
    \ Check if it exists when the following revision matters for your application.\n* Incorporate the revision r147, which includes robustness improvement and minor tweaks.\n\nBeware that due to this revision,\
    \ **the result of 32-bit version of 2.1 is NOT the same as that of 2.0**. E.g.,::\n\n    >>> mmh3.hash('foo') # in mmh3 2.0\n    -292180858\n    >>> mmh3.hash('foo') # in mmh3 2.1\n    -156908512\n\n\
    The results of hash64 and hash_bytes remain unchanged. Austin Appleby, the author of Murmurhash, ensured this revision was the final modification to MurmurHash3's results and any future changes would\
    \ be to improve performance only.\n\nLicense\n=======\n\n`CC0-1.0 <./LICENSE>`_.\n\nFAQ\n===\n\nHow can I use this module? Any tutorials?\n-----------------------------------------\n\nThe following\
    \ textbooks and tutorials are great sources to learn how to use mmh3 (and other hash algorithms in general) for high-performance computing.\n\n* Chapter 11: Using Less Ram in Micha Gorelick and Ian\
    \ Ozsvald. 2014. *High Performance Python: Practical Performant Programming for Humans*. O'Reilly Media. `ISBN: 978-1-4493-6159-4 <https://www.amazon.com/dp/1449361595>`_.\n* Duke University. `Efficient\
    \ storage of data in memeory <http://people.duke.edu/~ccc14/sta-663-2016/20B_Big_Data_Structures.html>`_.\n* Max Burstein. `Creating a Simple Bloom Filter <http://www.maxburstein.com/blog/creating-a-simple-bloom-filter/>`_.\n\
    * Bugra Akyildiz. `A Gentle Introduction to Bloom Filter <https://bugra.github.io/work/notes/2016-06-05/a-gentle-introduction-to-bloom-filter/>`_.\n\nSome results are different from other MurmurHash3-based\
    \ libraries.\n------------------------------------------------------------------\n\nBy default, mmh3 returns **signed** values for 32-bit and 64-bit versions and **unsigned** values for ```hash128```,\
    \ due to historical reasons. Please use the keyword argument ``signed`` to obtain a desired result.\n\nFor compatibility with Google Guava (Java), see https://stackoverflow.com/questions/29932956/murmur3-hash-different-result-between-python-and-java-implementation\n\
    \n\nI want to report errors/ask questions/send requests.\n----------------------------------------------------\n\nThank you for helping me to improve the library. Please make sure to post them *through\
    \ the issue tracking system of GitHub*. Issues sent directly to my email account may go unnoticed.\n\nAuthors\n=======\n\nMurmurHash3 was originally developed by Austin Appleby and distributed under\
    \ public domain.\n\n* http://code.google.com/p/smhasher/\n\nPorted and modified for Python by Hajime Senuma.\n\n* http://pypi.python.org/pypi/mmh3\n* http://github.com/hajimes/mmh3\n\nSee also\n========\n\
    \n* https://github.com/wc-duck/pymmh3: mmh3 in pure python (Fredrik Kihlander and Swapnil Gusani)\n* https://github.com/escherba/python-cityhash: Python bindings for CityHash (Eugene Scherba)\n* https://github.com/veelion/python-farmhash:\
    \ Python bindigs for FarmHash (Veelion Chong)\n* https://github.com/escherba/python-metrohash: Python bindings for MetroHash (Eugene Scherba)"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
